---
title: "Abhay_InitialWrangling"
author: "Abhay V Rao"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
#Examine the working directory
getwd()

#Import libraries
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(RColorBrewer)
library(cowplot)
```
Reading the shapefile on biogas. Examining its characteristics.

```{r}
biogas_sf<- st_read('../Data/biomethane/Biomethane.shp')
colnames(biogas_sf)

biogas_california_sf<- st_read('../Data/biomethane/Biomethane.shp') %>%
  filter(STATE_NAME == "California")

class(biogas_california_sf$NAME)

str(biogas_california_sf)
summary(biogas_california_sf)
st_crs(biogas_california_sf) # WGS 84, EPSG 4326
st_bbox(biogas_california_sf)
head(biogas_california_sf)

```

Preliminary map view and ggplot of methane generation potential from waste water 
treatment in California.

```{r}

mapView(biogas_california_sf, zcol = "TotalCH4t")

Total_ch4_plot <-ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=TotalCH4t)) + 
  scale_fill_continuous(type='viridis')+
  labs(title='Total CH4 Potential, CA (MT per year)',
  )
print(Total_ch4_plot)
 
WW_ch4_plot <- ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=WWTPCH4t)) + 
  scale_fill_continuous(type='viridis')+
  labs(title='Wastewater Derived CH4 Potential, CA (MT per year)',
  )
print(WW_ch4_plot)

Landfill_ch4_plot <- ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=LFGCH4t)) + 
  scale_fill_continuous(type='viridis')+
  labs(title='Landfill Derived CH4 Potential, CA (MT per year)',
  )
print(Landfill_ch4_plot)

OW_ch4_plot <- ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=OWCH4t)) + 
  scale_fill_continuous(type='viridis')+
  labs(title='Commercial Organic Waste Derived CH4 Potential, CA (MT per year)',
  )
print(OW_ch4_plot)

AM_ch4_plot <- ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=AMCH4t)) + 
  scale_fill_continuous(type='viridis')+
  labs(title='Animal Manure Derived CH4 Potential, CA (MT per year)',
  )
print(AM_ch4_plot)

 Combinedplot_CH4 <- plot_grid(Total_ch4_plot, WW_ch4_plot, Landfill_ch4_plot, 
                               OW_ch4_plot, AM_ch4_plot)      
  print(Combinedplot_CH4)
  

```

Wrangling the population dataset below:

```{r}
population_data <- read.csv('../Data/CalCountyPopulation/Population2020.csv')
population_data$Population <- as.numeric(gsub(",","",population_data$Population))
class(population_data$Population)
head(population_data)


class(population_data$NAME)

biogas_pop_join <- left_join(biogas_california_sf, population_data, by = c('NAME' = 'NAME'))
str(biogas_pop_join)
head(biogas_pop_join)
str(biogas_pop_sf)
biogas_pop_join$Population <- as.numeric(c("1661584",
"1159","39023","223344","45828","21491","1147788","27692",
"190345","990204","28060", "136101","180580","17930","892458","151090",
"64276","30600","10040682", "155925","259441","17319", "87110","273661","8853",
"14395","432977","138572","99417","3170345","391799","18844","2437864","1537948",
"61547","2162532","3323970","874784","751615","282517","765623","444895","1924379",
"273170","179267","2898","43516","444538","496801","546235","96315","64176",
"1254","463955","54147","845599","218774","77524"
))

mapView(biogas_pop_join, zcol = "Population")

```

Regressions 

```{r}

ggplot(biogas_pop_join,aes(x=Population,y=WWTPCH4t)) + 
  geom_line() + 
  geom_smooth(method=lm,se=FALSE)+
  labs(title='Population and CH4 potential from Wastewater Treatment', 
       subtitle= "California",y="CH4 Generation", 
       x="Population")
```

=======
```{r}
#SVI Analysis

svi2018_CA_raw <- read.csv('https://svi.cdc.gov/Documents/Data/2018_SVI_Data/CSV/States_Counties/California_COUNTY.csv',
  colClasses = c('FIPS' = 'factor')) %>% 
  select(COUNTY, FIPS, LOCATION, E_TOTPOP, E_POV, E_MINRTY)

str(svi2018_CA_raw)

svi_sf_join <- biogas_pop_join %>% 
  left_join(svi2018_CA_raw, by = c("FIPS" = "FIPS") )

str(svi_sf_join)

#Correlation and regressions between methane and impoverished population

cor.test(svi_sf_join$TotalCH4t,svi_sf_join$E_POV)#0.82
regression_pov_CH4<- lm(svi_sf_join$TotalCH4t~svi_sf_join$E_POV)
summary(regression_pov_CH4) #p-value: 8.476e-16

cor.test(svi_sf_join$LFGCH4t,svi_sf_join$E_POV) #0.78
regression_pov_LFGCH4<- lm(svi_sf_join$LFGCH4t~svi_sf_join$E_POV)
summary(regression_pov_LFGCH4) #p-value: 5.653e-13

cor.test(svi_sf_join$WWTPCH4t,svi_sf_join$E_POV) #0.97
regression_pov_WWTPCH4<- lm(svi_sf_join$WWTPCH4t~svi_sf_join$E_POV)
summary(regression_pov_WWTPCH4) #p-value: < 2.2e-16

cor.test(svi_sf_join$AMCH4t,svi_sf_join$E_POV) #0.05
regression_pov_AMCH4<- lm(svi_sf_join$AMCH4t~svi_sf_join$E_POV)
summary(regression_pov_AMCH4) #p-value: 0.6652

cor.test(svi_sf_join$OWCH4t,svi_sf_join$E_POV)#0.98
regression_pov_OWCH4<- lm(svi_sf_join$OWCH4t~svi_sf_join$E_POV)
summary(regression_pov_OWCH4) #p-value: < 2.2e-16

```

