---
title: "Analysis V2"
author: "Yinan"
date: "4/13/2022"
output: html_document
---

```{r setup, include=FALSE}
#Examine the working directory
getwd()

#Import libraries
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(RColorBrewer)
library(cowplot)

#Reading the shapefile on biogas. Examining its characteristics.

biogas_sf<- st_read('../Data/biomethane/Biomethane.shp')
colnames(biogas_sf)

biogas_california_sf<- st_read('../Data/biomethane/Biomethane.shp') %>%
  filter(STATE_NAME == "California")

class(biogas_california_sf$NAME)

# str(biogas_california_sf)
# summary(biogas_california_sf)
# st_crs(biogas_california_sf) # WGS 84, EPSG 4326
# st_bbox(biogas_california_sf)
# head(biogas_california_sf)

```

Preliminary map view and ggplot of methane generation potential from waste water 
treatment in California.

```{r}

mapView(biogas_california_sf, zcol = "WWTPCH4t")

ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=WWTPCH4t)) + 
  scale_fill_continuous(type='viridis')

```

Wrangling the population dataset below:

```{r}
#Read csv files.
population_data <- read.csv('../Data/CalCountyPopulation/Population2020.csv')
population_data$Population <- as.numeric(gsub(",","",population_data$Population))
class(population_data$Population)
head(population_data)

  
# Add population data to the biogas generation potential data. Combined two data with 'merge' funciton. 
biogas_pop_join <- merge(biogas_california_sf,population_data,by = "NAME", all = TRUE)
str(biogas_pop_join)
head(biogas_pop_join)
mapView(biogas_pop_join, zcol = "Population")

```


```{r,linear.regression}
# What factors affect biogas generation potential in different counties of California? Could it have potential correlations with the population size?
# Null Hypothesis: There is no correlation between population density and biogas generation potential.

cor.test(biogas_pop_join$TotalCH4t,biogas_pop_join$Population)
#cor:0.819
regression_pop_CH4<- lm(biogas_pop_join$TotalCH4t~biogas_pop_join$Population)
summary(regression_pop_CH4)
#p-value:4.22e-15
#Residual standard error: 20420 on 56 degrees of freedom
#Multiple R-squared: 0.6701
plot(regression_pop_CH4)


mytheme <- theme_classic(base_size = 12) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top") 

Plot_pop_CH4 <- 
  ggplot(biogas_pop_join, aes(x = TotalCH4t, y = Population,)) +
  geom_point(alpha=2, color = "Purple") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Biogas Generation Potential")+
  ggtitle("Biogas Generation Potential v.s. Population in California")+
  mytheme
  print(Plot_pop_CH4)  

# We ran a correlation test to test the strength and direction between California population and the total biogas generation potential.  We also ran a simple linear regression model to investigate whether these two variables involves a linear relationship. By looking at the residual plots, we can tell that the regression model fits our data but has outliers that disrupt the model accuracy. The p-value is 4.22e-15, indicating that the result is statistically significant. The multiple R-squared is 0.67, meaning that the independent variables can expalin 67% of the variations in biogas generation potential. Therefore, we are confident in rejecting the null hypothesis.
# Now we can say the total biogas generation potential in california does have a linear relationship with the population density. However, we still want to know how and what different sources is correlated with population. Subsequently, we ran the same test for each individual biogas sources
  
OW_Plot <- 
  ggplot(biogas_pop_join, aes(x = OWCH4t, y = Population)) +
  geom_point(alpha=2, color = "Red") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Organic Waste")+
  ggtitle("Organic Waste Potential")+
  mytheme
  print(OW_Plot)  

cor.test(biogas_pop_join$OWCH4t,biogas_pop_join$Population)
#cor: 0.96
regression_pop_OW<- lm(biogas_pop_join$OWCH4t~biogas_pop_join$Population)
summary(regression_pop_OW)
#p-value: < 2.2e-16
#Residual standard error: 515.6 on 56 degrees of freedom
#Multiple R-squared: 0.99
  
AM_Plot <- 
  ggplot(biogas_pop_join, aes(x = AMCH4t, y = Population)) +
  geom_point(alpha=2, color = "Blue") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Animal Manure")+
  ggtitle("Animal Manure Potential")+
  mytheme
  print(AM_Plot)
  
cor.test(biogas_pop_join$AMCH4t,biogas_pop_join$Population)
#cor: -0.0018
regression_pop_AM<- lm(biogas_pop_join$AMCH4t~biogas_pop_join$Population)
summary(regression_pop_AM)
#p-value: < 0.989
#Residual standard error: 14190 on 56 degrees of freedom
#Multiple R-squared: -0.01785 

print(AM_Plot)  
  
  
WWTP_Plot <- 
  ggplot(biogas_pop_join, aes(x = WWTPCH4t, y = Population)) +
  geom_point(alpha=2, color = "Green") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Wastewater")+
  ggtitle("Waste Water Potential")+
  mytheme
  print(WWTP_Plot)  
  
cor.test(biogas_pop_join$WWTPCH4t,biogas_pop_join$Population)
#cor: 0.99
regression_pop_WWTP<- lm(biogas_pop_join$WWTPCH4t~biogas_pop_join$Population)
summary(regression_pop_WWTP)
#p-value: < 2.2e-16
#Residual standard error: 1128 on 56 degrees of freedom
#Multiple R-squared:  0.984 
  
LF_Plot <- 
  ggplot(biogas_pop_join, aes(x = LFGCH4t, y = Population)) +
  geom_point(alpha=2, color = "Blue") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Landfill")+
  ggtitle("Landfill Potential")+
  mytheme
  print(LF_Plot) 
  
cor.test(biogas_pop_join$LFGCH4t,biogas_pop_join$Population)
#cor: 0.79
regression_pop_LF<- lm(biogas_pop_join$LFGCH4t~biogas_pop_join$Population)
summary(regression_pop_LF)
#p-value: < 1.926e-13
#Residual standard error: 11680 on 56 degrees of freedom
#Multiple R-squared:  0.6223 

Combinedplot <- plot_grid(OW_Plot,AM_Plot,WWTP_Plot,LF_Plot)
  print(Combinedplot)
  
  
#Based on the results from running correlation test and linear regression model for each of the biogas generation sources: Organic waste, Animal manure, Wastewater, and Landfill. We found out the the organic waste and wastewater contributes to the highest correlation to the population density, while Animal manure and landfill are less correlated. 
```
