---
title: "Abhay_InitialWrangling"
author: "Abhay V Rao"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
#Examine the working directory
getwd()

#Import libraries
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(RColorBrewer)
```
Reading the shapefile on biogas. Examining its characteristics.

```{r}
biogas_sf<- st_read('../Data/biomethane/Biomethane.shp')
colnames(biogas_sf)

biogas_california_sf<- st_read('../Data/biomethane/Biomethane.shp') %>%
  filter(STATE_NAME == "California")

class(biogas_california_sf$NAME)

str(biogas_california_sf)
summary(biogas_california_sf)
st_crs(biogas_california_sf) # WGS 84, EPSG 4326
st_bbox(biogas_california_sf)
head(biogas_california_sf)

```

Preliminary map view and ggplot of methane generation potential from waste water 
treatment in California.

```{r}

mapView(biogas_california_sf, zcol = "WWTPCH4t")

ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=WWTPCH4t)) + 
  scale_fill_continuous(type='viridis')

```

Wrangling the population dataset below:

```{r}
population_data <- read.csv('../Data/CalCountyPopulation/Population2020.csv')
population_data$Population <- as.numeric(gsub(",","",population_data$Population))
class(population_data$Population)
head(population_data)


class(population_data$NAME)

biogas_pop_join <- left_join(biogas_california_sf, population_data, by = c('NAME' = 'NAME'))
str(biogas_pop_join)
head(biogas_pop_join)
str(biogas_pop_sf)
biogas_pop_join$Population <- as.numeric(c("1661584",
"1159","39023","223344","45828","21491","1147788","27692",
"190345","990204","28060", "136101","180580","17930","892458","151090",
"64276","30600","10040682", "155925","259441","17319", "87110","273661","8853",
"14395","432977","138572","99417","3170345","391799","18844","2437864","1537948",
"61547","2162532","3323970","874784","751615","282517","765623","444895","1924379",
"273170","179267","2898","43516","444538","496801","546235","96315","64176",
"1254","463955","54147","845599","218774","77524"
))

mapView(biogas_pop_join, zcol = "Population")

```

