---
title: "InitialAnalysis"
author: "Yinan"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
#Examine the working directory
getwd()

#Import libraries
library(tidyverse)
library(lubridate)
library(sf)
library(mapview)
library(RColorBrewer)
library(cowplot)
```
Reading the shapefile on biogas. Examining its characteristics.

```{r}
biogas_sf<- st_read('../Data/biomethane/Biomethane.shp')
colnames(biogas_sf)

biogas_california_sf<- st_read('../Data/biomethane/Biomethane.shp') %>%
  filter(STATE_NAME == "California")

class(biogas_california_sf$NAME)

str(biogas_california_sf)
summary(biogas_california_sf)
st_crs(biogas_california_sf) # WGS 84, EPSG 4326
st_bbox(biogas_california_sf)
head(biogas_california_sf)

```

Preliminary map view and ggplot of methane generation potential from waste water 
treatment in California.

```{r}

mapView(biogas_california_sf, zcol = "WWTPCH4t")

ggplot(data=biogas_california_sf) +
  geom_sf(aes(fill=WWTPCH4t)) + 
  scale_fill_continuous(type='viridis')

```

Wrangling the population dataset below:

```{r}
population_data <- read.csv('../Data/CalCountyPopulation/Population2020.csv')
population_data$Population <- as.numeric(gsub(",","",population_data$Population))
class(population_data$Population)
head(population_data)


class(population_data$NAME)

biogas_pop_join <- left_join(biogas_california_sf, population_data, by = c('NAME' = 'NAME'))
str(biogas_pop_join)
head(biogas_pop_join)
biogas_pop_join$Population <- as.numeric(c("1661584",
"1159","39023","223344","45828","21491","1147788","27692",
"190345","990204","28060", "136101","180580","17930","892458","151090",
"64276","30600","10040682", "155925","259441","17319", "87110","273661","8853",
"14395","432977","138572","99417","3170345","391799","18844","2437864","1537948",
"61547","2162532","3323970","874784","751615","282517","765623","444895","1924379",
"273170","179267","2898","43516","444538","496801","546235","96315","64176",
"1254","463955","54147","845599","218774","77524"
))

mapView(biogas_pop_join, zcol = "Population")

```


```{r,linear.regression}
# Research Question: What factors affect the difference in biogas generation potential in California? 
# Null Hypothesis: There is no correlation between population density and biogas generation potential.
cor.test(biogas_pop_join$TotalCH4t,biogas_pop_join$Population)
#cor:0.819
regression_pop_CH4<- lm(biogas_pop_join$TotalCH4t~biogas_pop_join$Population)
summary(regression_pop_CH4)
#p-value:4.22e-15
#Residual standard error: 20420 on 56 degrees of freedom
#Multiple R-squared: 0.6701

plot(regression_pop_CH4)

mytheme <- theme_classic(base_size = 12) +
  theme(axis.text = element_text(color = "black"), 
        legend.position = "top") 

Plot_pop_CH4 <- 
  ggplot(biogas_pop_join, aes(x = TotalCH4t, y = Population,)) +
  geom_point(alpha=2, color = "Purple") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Biogas Generation Potential")+
  ggtitle("Biogas Generation Potential v.s. Population in California")+
  mytheme
  print(Plot_pop_CH4)  
  
#Based on previous analysis, we reject our null hypothesis because the biogas generation potential and population is posively correlated with a statistically significant p-value. However, we still want to know Which biogas source is contributing to the highest correlation with Population.
  
OW_Plot <- 
  ggplot(biogas_pop_join, aes(x = OWCH4t, y = Population)) +
  geom_point(alpha=2, color = "Red") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Organic Waste")+
  ggtitle("Organic Waste Methane Generation Potential")+
  mytheme
  print(OW_Plot)  

cor.test(biogas_pop_join$OWCH4t,biogas_pop_join$Population)
#cor: 0.96
regression_pop_OW<- lm(biogas_pop_join$OWCH4t~biogas_pop_join$Population)
summary(regression_pop_OW)
#p-value: < 2.2e-16
#Residual standard error: 515.6 on 56 degrees of freedom
#Multiple R-squared: 0.99
  
AM_Plot <- 
  ggplot(biogas_pop_join, aes(x = AMCH4t, y = Population)) +
  geom_point(alpha=2, color = "Blue") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Animal Manure")+
  ggtitle("Animal Manure Methane Generation Potential")+
  mytheme
  print(AM_Plot)
  
cor.test(biogas_pop_join$AMCH4t,biogas_pop_join$Population)
#cor: -0.0018
regression_pop_AM<- lm(biogas_pop_join$AMCH4t~biogas_pop_join$Population)
summary(regression_pop_AM)
#p-value: < 0.989
#Residual standard error: 14190 on 56 degrees of freedom
#Multiple R-squared: -0.01785 
  
WWTP_Plot <- 
  ggplot(biogas_pop_join, aes(x = WWTPCH4t, y = Population)) +
  geom_point(alpha=2, color = "Green") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Wastewater")+
  ggtitle("Waste Water Methane Generation Potential")+
  mytheme
  print(WWTP_Plot)  
  
cor.test(biogas_pop_join$WWTPCH4t,biogas_pop_join$Population)
#cor: 0.99
regression_pop_WWTP<- lm(biogas_pop_join$WWTPCH4t~biogas_pop_join$Population)
summary(regression_pop_WWTP)
#p-value: < 2.2e-16
#Residual standard error: 1128 on 56 degrees of freedom
#Multiple R-squared:  0.984 

LF_Plot <- 
  ggplot(biogas_pop_join, aes(x = LFGCH4t, y = Population)) +
  geom_point(alpha=2, color = "Blue") +
  geom_smooth(method = "lm", se = FALSE)+
  xlim(0, 110000) +
  ylim(0, 5.0e+06)+
  labs(y= "Population Density", x = "Landfill")+
  ggtitle("Landfill Methane Generation Potential")+
  mytheme
  print(LF_Plot) 
  
cor.test(biogas_pop_join$LFGCH4t,biogas_pop_join$Population)
#cor: 0.79
regression_pop_LF<- lm(biogas_pop_join$LFGCH4t~biogas_pop_join$Population)
summary(regression_pop_LF)
#p-value: < 1.926e-13
#Residual standard error: 11680 on 56 degrees of freedom
#Multiple R-squared:  0.6223 

  Combinedplot <- plot_grid(
    OW_Plot,AM_Plot,WWTP_Plot,LF_Plot
  )
  print(Combinedplot)
  



```
